USE [master]
GO

/****** Object:  Database [BD_MARKETING]    Script Date: 26/10/2023 19:35:30 ******/
CREATE DATABASE [BD_MARKETING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_MARKETING', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BD_MARKETING.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_MARKETING_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BD_MARKETING_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_MARKETING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_MARKETING] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_MARKETING] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_MARKETING] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_MARKETING] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_MARKETING] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_MARKETING] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_MARKETING] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_MARKETING] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_MARKETING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_MARKETING] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_MARKETING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_MARKETING] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_MARKETING] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_MARKETING] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_MARKETING] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_MARKETING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_MARKETING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_MARKETING] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_MARKETING] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_MARKETING] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_MARKETING] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_MARKETING] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_MARKETING] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_MARKETING] SET  MULTI_USER 
GO

ALTER DATABASE [BD_MARKETING] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_MARKETING] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_MARKETING] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_MARKETING] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_MARKETING] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_MARKETING] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_MARKETING] SET QUERY_STORE = ON
GO

ALTER DATABASE [BD_MARKETING] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BD_MARKETING] SET  READ_WRITE 
GO


USE BD_MARKETING;

CREATE TABLE CLIENTES (
 ID_CLIENTE INT PRIMARY KEY 
,NM_CLIENTE VARCHAR(250) NOT NULL
,ENDERECO VARCHAR(250) 
,UF VARCHAR(2)
,SEXO VARCHAR (1) NOT NULL
,TELEFONE VARCHAR(15)
,CPF VARCHAR(20) NOT NULL
,RG VARCHAR(20) NOT NULL
,EMAIL VARCHAR(100) NOT NULL

,DT_NASCIMENTO DATE NOT NULL);

CREATE TABLE CURSOS (
 ID_CURSO INT PRIMARY KEY
,NM_CURSO VARCHAR(50) NOT NULL
,TEMPO_DURACAO FLOAT(2) NOT NULL
,TIPO_CURSO VARCHAR(30) NOT NULL
,MODALIDADE_CURSO VARCHAR (50) NOT NULL
,VALOR_CURSO FLOAT NOT NULL);

CREATE TABLE VENDAS(
 ID_VENDA INT PRIMARY KEY
,DATA_HORA_VENDA DATETIME
,ID_CURSO INT
,NM_CURSO VARCHAR(50)
,ID_CLIENTE INT
,NM_CLIENTE VARCHAR(250)
,CANAL_VENDAS VARCHAR (50)-- SE COMPROU NO SITE, TELEVENDA
,MODALIDADE_CURSO VARCHAR (50)
,VALOR_CURSO FLOAT
,VALOR_DESCONTO FLOAT
,TIPO_DESCONTO VARCHAR(50)
,DESC_DESCONTO VARCHAR(250)
,VALOR_LIQUIDO FLOAT);

CREATE TABLE PROSPECCAO_VENDAS (

 ID_CADASTRO INT PRIMARY KEY 
,NM_ALUNO VARCHAR(250) NOT NULL
,ENDERECO VARCHAR(250) NOT NULL 
,CIDADE VARCHAR(50)
,UF VARCHAR(2)
,TELEFONE VARCHAR(15)
,CPF VARCHAR(20) NOT NULL
,RG VARCHAR(20) NOT NULL
,EMAIL VARCHAR(100) NOT NULL
,DT_NASCIMENTO DATE NOT NULL
,DEFICIENCIA VARCHAR (50)
,SEXO VARCHAR(1) NOT NULL
,ESTADO_CIVIL VARCHAR (30)
,NOME_MAE VARCHAR(100)
,NOME_PAI VARCHAR(100)
,CURSO_INTERESSE VARCHAR (50)
,CANAL VARCHAR(30)
,TEMPO_TELA TIMESTAMP
,INTERACOES INT

);